Source Code/Models/Thuoc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuoc()
        {
            this.ChiTietPhieuKhams = new HashSet<ChiTietPhieuKham>();
        }
    
        public int MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string CachDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuKham> ChiTietPhieuKhams { get; set; }
    }
}

Source Code/Areas/Admin/Controllers/ThuocController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Warehouse.Models;
using Warehouse.Services;

namespace Warehouse.Areas.Admin.Controllers
{
    [Authorize]
    public class ThuocController : Controller
    {
        ThuocService _thuocService = new ThuocService();

        #region CRUD
        public ActionResult Index()
        {
            return View(_thuocService.GetAll());
        }

        public ActionResult _CreateModal()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Thuoc thuoc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _thuocService.Add(thuoc);
                    return Json(new { status = 1, message = "Thêm thành công" });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(ModelState) });
        }

        public ActionResult _EditModal(int id)
        {
            Thuoc thuoc = _thuocService.GetByMaThuoc(id);
            if (thuoc == null)
            {
                return Redirect("/pages/404");
            }
            return PartialView(thuoc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Thuoc thuoc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _thuocService.Update(thuoc);
                    return Json(new { status = 1, message = "Sửa thành công" });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(ModelState) });
        }

        public ActionResult _DeleteModal(int Id)
        {
            Thuoc thuoc = _thuocService.GetByMaThuoc(Id);
            if (thuoc == null)
            {
                return Content("<p>Dữ liệu không tồn tại trong hệ thống!</p>");
            }
            return PartialView(thuoc);
        }


        // POST: Admin/Color/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Thuoc thuoc = _thuocService.GetByMaThuoc(id);
                if (thuoc == null)
                {
                    ModelState.AddModelError("", "Thuốc không tồn tại!");
                }
                if (ModelState.IsValid)
                {
                    _thuocService.Delete(thuoc);
                    return Json(new { status = 1 });
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(ModelState) });
        }
        #endregion

        [HttpPost]
        public JsonResult GetAll()
        {
            var thuocs = _thuocService.GetAll().Select(x => x.TenThuoc).ToArray();
            return Json(thuocs, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetThongTinThuoc(int maThuoc)
        {
            var thuoc = _thuocService.GetByMaThuoc(maThuoc);
            if(thuoc != null)
            {
                return Json(new { MaThuoc = thuoc.MaThuoc, TenThuoc = thuoc.TenThuoc, CachDung = thuoc.CachDung, DonVi = thuoc.DonVi, DonGia = thuoc.DonGia }, JsonRequestBehavior.AllowGet);
            }
            return Json(new Thuoc() { }, JsonRequestBehavior.AllowGet);
        }
    }
}

Source Code/Areas/Admin/Views/Thuoc/Index.cshtml
@model List<Thuoc>

@{
    ViewBag.Title = "Danh Sách Thuốc";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Styles{

}


@section scripts{
    <script>
        $(function () {
            $(document).on("submit", "form[name=frm]", function (e) {
                e.preventDefault();
                $.ajax({
                    url: $(this).attr("action"),
                    method: "Post",
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.status == 1) {
                            window.location.reload();
                        }
                        else {
                            ShowPopUpError(result.message);
                        }
                    },
                    error: function () {
                        ShowPopUpError("Lỗi ajax!");
                    }
                });
            });
        });
    </script>
}

<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Dashboard")"><i class="fa fa-dashboard"></i> Bảng Điều Khiển</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div>
                <p>
                    <a data-toggle="modal" href="@Url.Action("_CreateModal")" class="btn bg-purple btn-sm" data-target="#modal-createModal">Thêm Mới</a>
                </p>
            </div>
            <div class="box">
                <div class="box-body">

                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-middle table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="text-center">STT</th>
                                            <th>Tên Thuốc</th>
                                            <th>Đơn Vị</th>
                                            <th>Đơn Giá</th>
                                            <th>Cách Dùng</th>
                                            <th class="text-center col-sm-2">Thao tác</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ 
                                            int i = 1;
                                        }
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <td class="text-center">
                                                @i
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TenThuoc)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DonVi)
                                            </td>
                                            <td>
                                                @Warehouse.Models.Format.FormatCurrencyVND(item.DonGia)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CachDung)
                                            </td>
                                            <td>
                                                <a data-toggle="modal" data-target="#modal-editModal" href="@Url.Action("_EditModal", new { Id = item.MaThuoc })" class="btn bg-purple btn-sm"><i class="fa fa-edit"></i> Sửa</a>
                                                <a data-toggle="modal" data-target="#modal-deleteModal" href="@Url.Action("_DeleteModal", new { Id = item.MaThuoc })" class="btn btn-default btn-sm"><i class="fa fa-remove"></i> Xóa</a>
                                            </td>
                                        </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<div class="modal fade modal-ajax" id="modal-createModal">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade modal-ajax" id="modal-editModal">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade modal-ajax" id="modal-deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

 

Source Code/Areas/Admin/Views/Thuoc/_CreateModal.cshtml
@model Thuoc

@{
    Layout = null;
}

@using (Html.BeginForm("Create", "Thuoc", FormMethod.Post, new { name="frm" }))
{
    <div class="modal-header bg-purple">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Thêm Thuốc</h4>
    </div>

    <div class="modal-body form-horizontal">
        <!-- form start -->
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TenThuoc, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.TenThuoc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenThuoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonVi, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.DonVi, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DonVi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.DonGia, new { @class = "form-control divide" })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CachDung, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextAreaFor(m => m.CachDung, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CachDung, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn bg-purple pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-green">Thêm Mới</button>
    </div>
}
<script>
      $('.divide').divide({
            delimiter: '.',
            divideThousand: true, // 1,000..9,999
            delimiterRegExp: /[\.\,\s]/g
        }).keypress(function (key) {
            if (key.charCode < 48 || key.charCode > 57) return false;
        });
</script>
@Scripts.Render("~/bundles/jqueryval")

Source Code/Areas/Admin/Views/Thuoc/_DeleteModal.cshtml
@model Thuoc

@{
    Layout = null;
}

@using (Html.BeginForm("Delete", "Thuoc", new { Id = Model.MaThuoc }, FormMethod.Post, new { name = "frm" }))
{
    <div class="modal-header bg-red">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Xoá Thuốc</h4>
    </div>

    <div class="modal-body">
        <!-- form start -->
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5>Bạn có chắc muốn xoá thuốc @Model.TenThuoc ?</h5>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-red"><i class="fa fa-save"></i> Xoá</button>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

Source Code/Areas/Admin/Views/Thuoc/_EditModal.cshtml
@model Thuoc

@{
    Layout = null;
}

@using (Html.BeginForm("Edit", "Thuoc", new { Id = Model.MaThuoc }, FormMethod.Post, new { name="frm" }))
{
    <div class="modal-header bg-purple">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Sửa Thuốc</h4>
    </div>

    <div class="modal-body form-horizontal">
        <!-- form start -->
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.MaThuoc)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TenThuoc, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.TenThuoc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenThuoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonVi, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.DonVi, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DonVi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.DonGia, new { @class = "form-control divide" })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CachDung, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextAreaFor(m => m.CachDung, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CachDung, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn bg-purple pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-blue"><i class="fa fa-save"></i> Lưu</button>
    </div>
}
<script>
      $('.divide').divide({
            delimiter: '.',
            divideThousand: true, // 1,000..9,999
            delimiterRegExp: /[\.\,\s]/g
        }).keypress(function (key) {
            if (key.charCode < 48 || key.charCode > 57) return false;
        });
</script>
@Scripts.Render("~/bundles/jqueryval")