Source Code/Areas/Admin/Controllers/KhamBenhController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Warehouse.Models;
using Warehouse.Services;

namespace Warehouse.Areas.Admin.Controllers
{
    [Authorize]
    public class KhamBenhController : Controller
    {
        BenhNhanService _benhNhanService = new BenhNhanService();
        PhieuKhamService _phieuKhamnService = new PhieuKhamService();

        public ActionResult Index()
        {
            var khamBenhs = _benhNhanService.GetDanhSachKhamBenh();
            return View(khamBenhs);
        }

        public PartialViewResult _CreateModal()
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult _CreateModal(FormCollection formCollection)
        {  
            DateTime ngayKham;
            if(DateTime.TryParseExact(formCollection["NgayKham"].ToString(), "dd/MM/yyyy", null, System.Globalization.DateTimeStyles.None, out ngayKham) == false)
            {
                ModelState.AddModelError("NgayKham", "Ngày khám phải là ngày hợp lệ với định dạng dd/MM/yyyy (ví dụ 05/12/2020)!");
                return Json(new { status = 0, message = Warehouse.Models.Functions.GetAllErrorsPage(this.ModelState) }, JsonRequestBehavior.AllowGet);
            }
            List<BenhNhan> benhNhans = new List<BenhNhan>();
            for(int i = 1; i <= 5; i++)
            {
                if (formCollection["HoTen_" + i] != null && formCollection["HoTen_" + i].ToString() != "")
                {
                    BenhNhan benhNhanMoi = new BenhNhan()
                    {
                        HoTen = formCollection["HoTen_" + i].ToString(),
                        GioiTinh = formCollection["GioiTinh_" + i] != null ? (int.Parse(formCollection["GioiTinh_" + i].ToString()) == 1 ? true : false) : false,
                        NamSinh = formCollection["NamSinh_" + i] != null ? (int?)int.Parse(formCollection["NamSinh_" + i].ToString()) : null,
                        DiaChi = formCollection["DiaChi_" + i] 
                    };
                    if(_benhNhanService.KiemTraLuotKhamQua40Nguoi(ngayKham))
                    {
                        ModelState.AddModelError("", "Lượng khám trong ngày này đã vượt đủ 40 người. Không thể tạo thêm!");
                        break;
                    }

                    if (ModelState.IsValid)
                    {
                        _benhNhanService.Add(benhNhanMoi);
                        PhieuKham phieuKhamMoi = new PhieuKham()
                        {
                            MaBenhNhan = benhNhanMoi.MaBenhNhan,
                            NgayKham = ngayKham
                        };
                        _phieuKhamnService.Add(phieuKhamMoi);
                    }
                }
            }
            if(ModelState.IsValid)
            {
                return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = 0, message = Warehouse.Models.Functions.GetAllErrorsPage(this.ModelState) }, JsonRequestBehavior.AllowGet);
        }
    }
}

Source Code/Areas/Admin/Views/KhamBenh/Index.cshtml
@model List<BenhNhan>
@{
    ViewBag.Title = "Danh Sách Khám Bệnh";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link href="~/Scripts/DatePicker/themes/jquery-ui.css" rel="stylesheet" />

}

@section scripts{
    <!-- DataTables -->
    <script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/DatePicker/jquery-ui.js"></script>
    <script src="~/Scripts/DatePicker/jquery.ui.datepicker-vi.js"></script>
    <script type="text/javascript">
        $(function () {

            $('#tblData').DataTable({
                'ordering': false,
                'searching': false,
                'lengthChange': false,
                'info': false
            });

            $(document).on("submit", "form[name=frm]", function (e) {
                e.preventDefault();
                $.ajax({
                    url: $(this).attr("action"),
                    method: "Post",
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.status == 1) {
                            window.location.reload();
                        }
                        else {
                            ShowPopUpError(result.message);
                        }
                    },
                    error: function () {
                        ShowPopUpError("Lỗi ajax!");
                    }
                });
            });


        });
    </script>
}

<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                <a href="@Url.Action("_CreateModal","KhamBenh")" class="btn btn-success" data-toggle="modal" data-target="#modal-themKhamBenh">Thêm Mới</a>
                            </p>
                            <div class="table-responsive">
                                <table id="tblData" class="table table-bordered" method="post">
                                    <thead>
                                        <tr>
                                            <th class="text-center">STT</th>
                                            <th>Họ Tên</th>
                                            <th class="text-center">Giới Tính</th>
                                            <th>Năm Sinh</th>
                                            <th>Địa Chỉ</th>
                                            <th>Ngày Khám</th>
                                            <th>Tạo Phiếu Khám</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                            int i = 1;
                                        }
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <td class="text-center">
                                                @i
                                            </td>
                                            <td>
                                                @Html.DisplayFor(m => item.HoTen)
                                            </td>
                                            <td class="text-center">
                                                @if (item.GioiTinh == true)
                                                {
                                                    <span>Nam</span>
                                                }
                                                else
                                                {
                                                    <span>Nữ</span>
                                                }
                                            </td>
                                            <td>
                                                @Html.DisplayFor(m => item.NamSinh)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(m => item.DiaChi)
                                            </td>
                                            <td>
                                                @(item.PhieuKham.NgayKham.ToString("dd/MM/yyyy"))
                                            </td>
                                            <td>
                                                <a href="@Url.Action("_CreateModal", "PhieuKham", new { MaBenhNhan = item.MaBenhNhan })" data-toggle="modal" data-target="#modal-themPhieuKhamBenh" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Tạo Phiếu Khám</a>
                                            </td>
                                        </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>


<div class="modal fade modal-ajax" id="modal-themKhamBenh">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

        </div>
    </div>
</div>


<div class="modal fade modal-ajax" id="modal-themPhieuKhamBenh">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

        </div>
    </div>
</div>

Source Code/Areas/Admin/Views/KhamBenh/_CreateModal.cshtml
 

 <script>
     $(".datepicker").datepicker($.datepicker.regional["vi"]);
 </script>

<form action="@Url.Action("_CreateModal")" method="post" name="frm" class="form-horizontal">
    <div class="modal-header bg-green">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Lập Danh Sách Khám Bệnh</h4>
    </div>
    <div class="modal-body">
        <div class="table-responsive">
            <table class="table table-bordered table-middle" method="post">
                <thead>
                    <tr class="bg-dark">
                        <th class="text-center">
                            BM1
                        </th>
                        <th colspan="4"  >
                            DANH SÁCH KHÁM BỆNH
                        </th>
                    </tr>
                    <tr>
                        <td class="text-center" colspan="5">
                            <label class="col-sm-4 control-label">Ngày khám</label>
                            <div class="col-sm-4">
                                <input type="text" name="NgayKham" class="form-control datepicker" />
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center">STT</th>
                        <th>Họ tên</th>
                        <th>Giới tính</th>
                        <th>Năm sinh</th>
                        <th>Địa chỉ</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i <= 5; i++)
                    {
                        <tr>
                            <td class="text-center">
                                <span>@i</span>
                            </td>
                            <td>
                                <input type="text" name="HoTen_@i" class="form-control" />
                            </td>
                            <td>
                                <select class="form-control"  name="GioiTinh_@i">
                                    <option value="1">Nam</option>
                                    <option value="0">Nữ</option>
                                </select>
                            </td>
                            <td>
                                <input type="number" min="1900"  max="@DateTime.Now.Year" class="form-control" name="NamSinh_@i" />
                            </td>
                            <td>
                                <input type="text" name="DiaChi_@i" class="form-control" />
                            </td>
                        </tr>
                         
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-green">Thêm Mới</button>
    </div>
</form>