Source Code/Models/PhieuKham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.ChiTietPhieuKhams = new HashSet<ChiTietPhieuKham>();
        }
    
        public System.DateTime NgayKham { get; set; }
        public string TrieuChung { get; set; }
        public string DuDoanLoaiBenh { get; set; }
        public int MaBenhNhan { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuKham> ChiTietPhieuKhams { get; set; }
        public virtual HoaDonThanhToan HoaDonThanhToan { get; set; }
    }
}

Source Code/Areas/Admin/Controllers/PhieuKhamController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Warehouse.Models;
using Warehouse.Services;

namespace Warehouse.Areas.Admin.Controllers
{
    [Authorize]
    public class PhieuKhamController : Controller
    {
        PhieuKhamService _phieuKhamService = new PhieuKhamService();
        ChiTietPhieuKhamService _chiTietPhieuKhamService = new ChiTietPhieuKhamService();
        BenhNhanService _benhNhanService = new BenhNhanService();
        ThuocService _thuocService = new ThuocService();

        public ActionResult Index()
        {
            var phieuKhams = _phieuKhamService.GetAll();
            return View(phieuKhams);
        }

        public ActionResult _DetailModal(int maBenhNhan)
        {
            var phieuKham = _phieuKhamService.GetPhieuKhamCuaBenhNhan(maBenhNhan);
            if(phieuKham == null)
            {
                return Content("Không có dữ liệu!");
            }
            ViewBag.ChiTietPhieuKhams = _chiTietPhieuKhamService.GetByMaPhieuKham(phieuKham.MaBenhNhan);
            return PartialView(phieuKham);
        }

        public PartialViewResult _CreateModal(int maBenhNhan)
        {
            ViewBag.BenhNhan = _benhNhanService.GetByMaBenhNhan(maBenhNhan);
            ViewBag.Thuocs = _thuocService.GetAll();
            return PartialView();
        }

        [HttpPost]
        public JsonResult _CreateModal(int maBenhNhan, FormCollection formCollection)
        {
            PhieuKham phieuKham = _phieuKhamService.GetPhieuKhamCuaBenhNhan(maBenhNhan);
            if(phieuKham != null)
            {
                phieuKham.TrieuChung = formCollection["TrieuChung"];
                phieuKham.DuDoanLoaiBenh = formCollection["DuDoanLoaiBenh"];
            }
            List<ChiTietPhieuKham> chiTietPhieuKhams = new List<ChiTietPhieuKham>();
            for(int i = 1; i <= 5; i++)
            {
                if (formCollection["Thuoc_" + i] != null && formCollection["Thuoc_" + i].ToString() != "")
                {
                    Thuoc thuoc = _thuocService.GetByMaThuoc(int.Parse(formCollection["Thuoc_" + i].ToString()));
                    ChiTietPhieuKham chiTietPhieuKhamMoi = new ChiTietPhieuKham()
                    {
                        MaPhieuKham = phieuKham.MaBenhNhan,
                        MaThuoc = thuoc.MaThuoc,
                        SoLuong = formCollection["SoLuong_" + i] != null ? (byte?)byte.Parse(formCollection["SoLuong_" + i].ToString()) : null,
                    };
                    chiTietPhieuKhamMoi.ThanhTien = thuoc.DonGia == null ? null : (int?)(chiTietPhieuKhamMoi.SoLuong * thuoc.DonGia.Value);
                    chiTietPhieuKhams.Add(chiTietPhieuKhamMoi);
                }
            }
            if(ModelState.IsValid)
            {
                _phieuKhamService.Update(phieuKham);
                _chiTietPhieuKhamService.AddList(chiTietPhieuKhams);
                return Json(new { status = 1 });
            }
            return Json(new { status = 0, message = Warehouse.Models.Functions.GetAllErrorsPage(this.ModelState) });
        }

    }
}

Source Code/Areas/Admin/Views/PhieuKham/Index.cshtml
@model List<PhieuKham>
@{
    ViewBag.Title = "Danh Sách Phiếu Khám Bệnh";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link href="~/Scripts/DatePicker/themes/jquery-ui.css" rel="stylesheet" />

}

@section scripts{
    <!-- DataTables -->
    <script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/DatePicker/jquery-ui.js"></script>
    <script src="~/Scripts/DatePicker/jquery.ui.datepicker-vi.js"></script>
    <script type="text/javascript">
        $(function () {

            $('#tblData').DataTable({
                'ordering': false,
                'searching': false,
                'lengthChange': false,
                'info': false
            });

            $(document).on("submit", "form[name=frm]", function (e) {
                e.preventDefault();
                $.ajax({
                    url: $(this).attr("action"),
                    method: "Post",
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.status == 1) {
                            window.location.reload();
                        }
                        else {
                            ShowPopUpError(result.message);
                        }
                    },
                    error: function () {
                        ShowPopUpError("Lỗi ajax!");
                    }
                });
            });

            var thuocs = [];
            $.post("@Url.Action("GetAll","Thuoc")", function (result) {
                thuocs = result;
            });
        });
    </script>
}

<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            
                            <div class="table-responsive">
                                <table id="tblData" class="table table-bordered" method="post">
                                    <thead>
                                        <tr>
                                            <th class="text-center">STT</th>
                                            <th>Họ Tên</th>
                                            <th class="text-center">Giới Tính</th>
                                            <th>Năm Sinh</th>
                                            <th>Địa Chỉ</th>
                                            <th>Ngày Khám</th>
                                            <th>Xem Phiếu Khám</th>
                                            <th>Thanh Toán</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                            int i = 1;
                                        }
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td class="text-center">
                                                    @i
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => item.BenhNhan.HoTen)
                                                </td>
                                                <td class="text-center">
                                                    @if (item.BenhNhan.GioiTinh == true)
                                                    {
                                                        <span>Nam</span>
                                                    }
                                                    else
                                                    {
                                                        <span>Nữ</span>
                                                    }
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => item.BenhNhan.NamSinh)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => item.BenhNhan.DiaChi)
                                                </td>
                                                <td>
                                                    @(item.NgayKham.ToString("dd/MM/yyyy"))
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("_DetailModal", "PhieuKham", new { MaBenhNhan = item.MaBenhNhan })" data-toggle="modal" data-target="#modal-xemPhieuKhamBenh" class="btn bg-orange btn-sm"><i class="fa fa-pencil"></i> Xem Phiếu Khám</a>
                                                </td>
                                                <td>
                                                    @if(item.HoaDonThanhToan != null)
                                                    {
                                                        <button type="button" disabled class="btn btn-default btn-sm"><i class="fa fa-check"></i> Đã thanh toán</button>
                                                    }
                                                    else
                                                    {
                                                        <a href="@Url.Action("Create", "HoaDonThanhToan", new { maBenhNhan = item.MaBenhNhan })" class="btn btn-sm bg-red">Thanh toán</a>
                                                    }
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>


<div class="modal fade modal-ajax" id="modal-xemPhieuKhamBenh">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

        </div>
    </div>
</div>

Source Code/Areas/Admin/Views/PhieuKham/_CreateModal.cshtml
@{
    BenhNhan benhNhan = ViewBag.BenhNhan;
}


<script>
    $("select[data-name=Thuoc]").change(function () {
        var index = $(this).attr("data-index");
        $.post("@(Url.Action("GetThongTinThuoc","Thuoc"))", { maThuoc: $(this).val() }, function (data) {
            $("input[name=DonVi_" + index + "]").val(data.DonVi);
            $("input[name=CachDung_" + index + "]").val(data.CachDung);
        });
    });
    $("select[data-name=Thuoc]").change().bind();
</script>

<form method="post" action="@Url.Action("_CreateModal","PhieuKham")" name="frm" class="form-horizontal">
    <input type="hidden" name="MaBenhNhan" value="@benhNhan.MaBenhNhan" />
    <div class="modal-header bg-green">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">PHIẾU KHÁM BỆNH</h4>
    </div>
    <div class="modal-body">
        <div class="table-responsive">
            <table class="table table-bordered table-middle" method="post">
                <thead>
                    <tr class="bg-dark">
                        <th class="text-center">
                            BM2
                        </th>
                        <th colspan="4">
                            PHIẾU KHÁM BỆNH
                        </th>
                    </tr>
                    <tr>
                        <td class="text-center" colspan="5">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Họ tên</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@benhNhan.HoTen" class="form-control" />
                                        </div>

                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Ngày khám</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@(benhNhan.PhieuKham.NgayKham.ToString("dd/MM/yyyy"))" class="form-control" />
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Triệu chứng</label>
                                        <div class="col-sm-8">
                                            <input type="text" name="TrieuChung" required="" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Loại bệnh</label>
                                        <div class="col-sm-8">
                                            <input type="text" name="DuDoanLoaiBenh" required class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </td>
                    </tr>
                    <tr>
                        <th class="text-center">STT</th>
                        <th>Thuốc</th>
                        <th>Đơn vị</th>
                        <th>Cách dùng</th>
                        <th>Số lượng</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i <= 5; i++)
                    {
                    <tr>
                        <td class="text-center">
                            <span>@i</span>
                        </td>
                        <td>
                            <select class="form-control" data-name="Thuoc" data-index="@i" name="Thuoc_@i">
                                <option value="">Chọn thuốc</option>
                                @foreach (Thuoc thuocItem in ViewBag.Thuocs)
                                {
                                    <option value="@thuocItem.MaThuoc">@thuocItem.TenThuoc</option>
                                }
                            </select>
                        </td>
                        <td>
                            <input type="text" class="form-control" name="DonVi_@i" readonly="readonly" />
                        </td>
                        <td>
                            <input type="text" class="form-control" name="CachDung_@i" readonly="readonly" />
                        </td>
                        <td>
                            <input type="number" min="0" step="1" class="form-control" name="SoLuong_@i" />
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-green">Thêm Mới</button>
    </div>
</form>

Source Code/Areas/Admin/Views/PhieuKham/_DetailModal.cshtml
@model PhieuKham


<form method="post" name="frm" class="form-horizontal">
    <div class="modal-header bg-green">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">PHIẾU KHÁM BỆNH</h4>
    </div>
    <div class="modal-body">
        <div class="table-responsive">
            <table class="table table-bordered table-middle" method="post">
                <thead>
                    <tr class="bg-dark">
                        <th class="text-center">
                            BM2
                        </th>
                        <th colspan="4">
                            PHIẾU KHÁM BỆNH
                        </th>
                    </tr>
                    <tr>
                        <td class="text-center" colspan="5">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Họ tên</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@Model.BenhNhan.HoTen" class="form-control" />
                                        </div>

                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Ngày khám</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@(Model.NgayKham.ToString("dd/MM/yyyy"))" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Triệu chứng</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@Model.TrieuChung" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Loại bệnh</label>
                                        <div class="col-sm-8">
                                            <input type="text" readonly value="@Model.DuDoanLoaiBenh" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th class="text-center">STT</th>
                        <th>Thuốc</th>
                        <th>Đơn vị</th>
                        <th>Số lượng</th>
                        <th>Cách dùng</th>
                    </tr>
                </thead>
                <tbody>
                    @{ 
                        int i = 1;
                    }
                    @foreach(ChiTietPhieuKham chiTietPhieuKham in ViewBag.ChiTietPhieuKhams)
                    {
                        <tr>
                            <td class="text-center">
                                <span>@i</span>
                            </td>
                            <td>
                                <input type="text" readonly value="@chiTietPhieuKham.Thuoc.TenThuoc" class="form-control" />
                            </td>
                            <td>
                                <input type="text" value="@chiTietPhieuKham.Thuoc.DonVi" class="form-control" readonly="readonly" />
                            </td>
                            <td>
                                <input type="number" readonly value="@chiTietPhieuKham.SoLuong" class="form-control"  />
                            </td>
                            <td>
                                <input type="text" value="@chiTietPhieuKham.Thuoc.CachDung" class="form-control" readonly="readonly" />
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
    </div>
</form>