Source Code/Areas/Admin/Controllers/AspNetUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Warehouse.Models;
using Microsoft.AspNet.Identity;
using System.Configuration;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;

namespace Warehouse.Areas.Admin.Controllers
{
    [Authorize]
    public class AspNetUserController : Controller
    {

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
       
        public AspNetUserController()
        {

        }

        public AspNetUserController(ApplicationSignInManager signInManager, ApplicationUserManager userManager)
        {
            SignInManager = signInManager;
            UserManager = userManager;
        }


        #region Public Property 
        public string UserId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        #endregion

        public PartialViewResult _UserLoggedPartial()
        {
            ApplicationUser applicationUser = UserManager.FindById(UserId);
            return PartialView(applicationUser);
        }

        public PartialViewResult _UserPanelPartial()
        {
            ApplicationUser applicationUser = UserManager.FindById(UserId);
            return PartialView(applicationUser);
        }

        public ViewResult ProfileUser()
        {
            ApplicationUser model = UserManager.FindById(UserId);
            ViewBag.Title = "Hồ sơ cá nhân";
            UpdateInfoViewModel updateInfoViewModel = new UpdateInfoViewModel()
            {
                Address = model.Address,
                UserName = model.UserName,
                FullName = model.FullName,
                Id = model.Id,
                PhoneNumber = model.PhoneNumber,
                RoleId = ViewBag.RoleId,
                Avatar = model.Avatar,
                Email = model.Email
            };
            return View(updateInfoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProfileUser([Bind(Exclude = "UserName")] UpdateInfoViewModel updateInfoViewModel)
        {
            var model = UserManager.FindById(UserId);
            if (ModelState.IsValid)
            {
                model.FullName = updateInfoViewModel.FullName;
                model.Address = updateInfoViewModel.Address;
                model.Email = updateInfoViewModel.Email;
                model.PhoneNumber = updateInfoViewModel.PhoneNumber;
                UserManager.Update(model);
                return RedirectToAction("ProfileUser", new { Id = updateInfoViewModel.Id });
            }
            ViewBag.Title = "Hồ sơ cá nhân";
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeAvatar(string userId, string base64String)
        {
            if (User.IsInRole("Admin") == false)
            {
                userId = this.UserId;
            }
            if (!string.IsNullOrEmpty(base64String))
            {
                var model = UserManager.FindById(userId);
                try
                {
                    base64String = base64String.Substring(base64String.IndexOf(',') + 1);
                    string newAvatar = model.UserName + DateTime.Now.Ticks.ToString() + ".jpg";
                    Functions.SaveFileFromBase64(Server.MapPath("~/Photos/Users/" + newAvatar), base64String);
                    model.Avatar = newAvatar;
                }
                catch (Exception ex)
                {
                    return RedirectToAction("ProfileUser", new { Id = userId });
                }
                UserManager.Update(model);
            }

            return RedirectToAction("ProfileUser", new { Id = userId });
        }

        [AllowAnonymous]
        public ActionResult Employees()
        {
            List<ApplicationUser> applicationUsers = UserManager.Users.ToList();
            return View(applicationUsers);
        }

        [Authorize(Users = "admin")]
        public ActionResult _EditEmployeeModal(string Id)
        {
            ApplicationUser applicationUser = UserManager.FindById(Id);
            if (applicationUser == null)
            {
                return Content("<p>Dữ liệu không tồn tại trong hệ thống!</p>");
            }
            return PartialView(applicationUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin")]
        public JsonResult EditEmployee([Bind(Include = "Id,FullName,PhoneNumber,Address")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = UserManager.FindById(applicationUser.Id);
                try
                {
                    user.FullName = applicationUser.FullName;
                    user.PhoneNumber = applicationUser.PhoneNumber;
                    user.Address = applicationUser.Address;
                    UserManager.Update(user);
                    return Json(new { status = 1, message = "Update success." }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(this.ModelState) });
        }


        [Authorize(Users = "admin")]
        [AllowAnonymous]
        /// <summary>
        /// Thêm Nhân Viên
        /// </summary>
        /// <returns></returns>
        public ActionResult _CreateModal()
        {
            return PartialView(new CreateUserViewModel());
        }

        //[Authorize(Users = "admin")]
        /// <summary>
        /// Thêm Nhân viên
        /// </summary>
        /// <param name="createUserViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<JsonResult> Create(CreateUserViewModel createUserViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser()
                {
                    UserName = createUserViewModel.UserName,
                    Email = createUserViewModel.Email,
                    FullName = createUserViewModel.FullName,
                    Avatar = "user.png",
                    DateRegister = DateTime.Now,
                    EmailConfirmed = true
                };
                try
                {
                    IdentityResult result = await UserManager.CreateAsync(user, createUserViewModel.Password);
                    if (result.Succeeded)
                    {
                        return Json(new { status = 1, message = "Thêm thành công" });
                    }
                    else
                    {
                        AddErrors(result);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(ModelState) });
        }

        [Authorize(Users = "admin")]
        public ActionResult _DeleteModal(string Id)
        {
            ApplicationUser applicationUser = UserManager.FindById(Id);
            if (applicationUser == null)
            {
                return Content("<p>Dữ liệu không tồn tại trong hệ thống!</p>");
            }
            return PartialView(applicationUser);
        }

        [Authorize(Users = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(string Id)
        {
            try
            {
                ApplicationUser user = await UserManager.FindByIdAsync(Id);
                await UserManager.DeleteAsync(user);
                return Json(new { status = 1, message = "Update success" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return Json(new { status = 0, message = Functions.GetAllErrorsPage(this.ModelState) }, JsonRequestBehavior.AllowGet);
        }


        public ViewResult Lock(string Id)
        {
            ApplicationUser aspNetUser = UserManager.FindById(Id);
            return View(aspNetUser);
        }


        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            if (ModelState.IsValid)
            {
                var result = UserManager.ChangePassword(UserId, changePasswordViewModel.OldPassword, changePasswordViewModel.NewPassword);
                if (result.Succeeded)
                {
                    var user = UserManager.FindById(UserId);
                    if (user != null)
                    {
                        SignInManager.SignIn(user, isPersistent: false, rememberBrowser: false);
                    }
                    return Json(new { status = 1, message = "Đổi mật khẩu thành công." }, JsonRequestBehavior.AllowGet);
                }

Source Code/Areas/Admin/Views/AspNetUser/Employees.cshtml
@model List<ApplicationUser>
@{
    ViewBag.Title = "Danh Sách Nhân Viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}

@section scripts{
    <!-- DataTables -->
    <script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#tblAspNetUser').DataTable({
                'ordering': true,
                'searching': true,
                'lengthChange': true,
                'info': true,
                columnDefs: [{ orderable: false, targets: [0, 4] }],
            });
            $(document).on("submit", "form[name=frm]", function (e) {
                e.preventDefault();
                $.ajax({
                    url: $(this).attr("action"),
                    method: "Post",
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.status == 1) {
                            window.location.reload();
                        }
                        else {
                            ShowPopUpError(result.message);
                        }
                    },
                    error: function () {
                        ShowPopUpError("Lỗi ajax!");
                    }
                });
            });
        });
    </script>
}

<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Bảng điều khiển</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                <a href="@Url.Action("_CreateModal")" class="btn btn-success" data-toggle="modal" data-target="#modal-createEmployee">Thêm Nhân Viên</a>
                            </p>
                            <div class="table-responsive">
                                <table id="tblAspNetUser" class="table table-bordered table-striped table-middle" method="post">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2 col-sm-4">Họ tên</th>
                                            <th>Email</th>
                                            <th>Điện thoại</th>
                                            <th>Địa chỉ</th>
                                            @if (User.Identity.Name == "admin")
                                            {
                                            <th class="col-md-2">Thao tác</th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (ApplicationUser applicationUser in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(m => applicationUser.FullName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => applicationUser.Email)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => applicationUser.PhoneNumber)
                                                </td>
                                                <td>
                                                   @applicationUser.Address
                                                </td>
                                                @if (User.Identity.Name == "admin")
                                                {
                                                <td>
                                                    <a href="@Url.Action("_EditEmployeeModal", "AspNetUser", new { Id = applicationUser.Id })" data-toggle="modal" data-target="#modal-editEmployee" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Sửa </a>
                                                    <a data-target="#modal-deleteUser" data-toggle="modal" href="@Url.Action("_DeleteModal", new { Id = applicationUser.Id })" class="btn btn-xs btn-danger"><i class="fa fa-remove"></i> Xóa</a>
                                                </td>
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<div class="modal fade modal-ajax" id="modal-createEmployee">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade modal-ajax" id="modal-editEmployee">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<div class="modal fade modal-ajax" id="modal-deleteUser">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.row -->

Source Code/Areas/Admin/Views/AspNetUser/ProfileUser.cshtml
@model UpdateInfoViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ChangePasswordViewModel changePasswordViewModel = new ChangePasswordViewModel();
}
@section styles{
    <link href="~/dist/css/canvasCrop.css" rel="stylesheet" />
    <style>
        .cropped {
            position: absolute;
            right: -230px;
            top: 0;
            width: 200px;
            border: 1px #ddd solid;
            height: 460px;
            padding: 4px;
            box-shadow: 0px 0px 12px #ddd;
            text-align: center;
        }

        .imageBox {
            position: relative;
            height: 250px;
            width: 400px;
            border: 1px solid #aaa;
            background: #fff;
            overflow: hidden;
            background-repeat: no-repeat;
            cursor: move;
            box-shadow: 4px 4px 12px #B0B0B0;
        }

            .imageBox .thumbBox {
                position: absolute;
                top: 50%;
                left: 50%;
                width: 200px;
                height: 200px;
                margin-top: -100px;
                margin-left: -100px;
                box-sizing: border-box;
                border: 1px solid rgb(102, 102, 102);
                box-shadow: 0 0 0 1000px rgba(0, 0, 0, 0.5);
                background: none repeat scroll 0% 0% transparent;
            }

            .imageBox .spinner {
                position: absolute;
                top: 0;
                left: 0;
                bottom: 0;
                right: 0;
                text-align: center;
                line-height: 400px;
                background: rgba(0,0,0,0.7);
            }
    </style>
}
@section scripts{
    <script src="~/dist/js/jquery.canvasCrop.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function(){
        var rot = 0,ratio = 1;

        $('#upload-file').on('change', function(){
            var reader = new FileReader();
            reader.onload = function(e) {
                CanvasCrop = $.CanvasCrop({
                    cropBox : ".imageBox",
                    imgSrc : e.target.result,
                    limitOver : 2
                });
                rot =0 ;
                ratio = 1;

            }

            reader.readAsDataURL(this.files[0]);
            console.log(this);
            this.value = "";
            $("#crop").removeClass("hide");
            $("#btnLuu").addClass("hide");
        });

        $("#crop").on("click",function(){
            var src = CanvasCrop.getDataURL("jpeg");
            $("#modal-crop-image .modal-body").append("<img src='" + src + "' />");
            $("#file").val(src);
            $("#btnLuu").removeClass("hide");
            });

        console.log("ontouchend" in document);

    })
    </script>
    <script type="text/javascript">
        function ChangePasswordSuccess(response) {
            if (response.status == 1) {
                ShowPopUpSuccess("Đổi mật khẩu thành công. Trang sẽ tự tải lại sau 3 giây.");
                setTimeout(function () {
                    window.location.reload();
                }, 3000);
            }
            else {
                ShowPopUpError(response.message);
            }
        }
        function SetPasswordSuccess(response) {
            if (response.status == 1) {
                ShowPopUpSuccess("Đặt lại mật khẩu thành công. Trang sẽ tự tải lại sau 3 giây.");
                setTimeout(function () {
                    window.location.reload();
                }, 3000);
            }
            else {
                ShowPopUpError(response.message);
            }
        }
    </script>
}

<div class="modal fade" id="modal-crop-image">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-purple">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Thay ảnh đại diện</h4>
            </div>
            <div class="modal-body">
                <div class="box-body">
                    @using (Html.BeginForm("ChangeAvatar", "AspNetUser", FormMethod.Post))
                    {
                        <input type="hidden" name="userId" value="@Model.Id" />
                        @Html.AntiForgeryToken()
                        <div class="imageBox">
                            <div class="mask"></div>
                            <div class="thumbBox"></div>
                            <div class="spinner" style="display: none">Loading...</div>
                        </div>
                        <div class="upload-wapper">
                            <br />
                            Chọn 1 hình
                            <input type="file" id="upload-file" value="Upload"><br />
                            <button type="button" class="btn btn-primary hide" id="crop">Crop</button>
                            <button type="submit" class="btn btn-danger hide" id="btnLuu"><i class="fa fa-save"></i> Lưu</button>
                            <input type="hidden" name="base64String" id="file" />
                        </div>
                    }
                </div>
            </div>
            <div class="modal-footer text-right">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Trang chủ </a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-3">
            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img style="cursor:pointer" title="Đổi hình" data-placement="bottom" class="profile-user-img img-responsive img-circle" src="~/Photos/Users/@Model.Avatar" alt="@Model.Avatar">
                    <h3 class="profile-username text-center">@Model.FullName</h3>
                    <h5 class="text-center text-info">@ViewBag.RoleId</h5>
                    @if (User.Identity.Name == Model.UserName)
                    {
                        <p class="text-center">
                            <input id="avatar" type="hidden" name="avatar">
                            <button type="button" data-toggle="modal" data-target="#modal-crop-image" id="btnDoiHinh" class="btn btn-default btn-xs"><i class="fa fa-image"></i> Đổi hình</button>
                        </p>
                    }
                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <span>Tài khoản:</span> <label class="pull-right text-info">@Model.UserName</label>
                        </li>
                        <li class="list-group-item">
                            <span>Email:</span> <label class="pull-right text-info">@Model.Email</label>
                        </li>
                        <li class="list-group-item">
                            <span>Điện thoại:</span> <label class="pull-right text-info">@Model.PhoneNumber</label>
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">

            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#settings" data-toggle="tab">Thông tin</a></li>
                    <li><a href="#changepassword" data-toggle="tab">Đổi mật khẩu</a></li>
                </ul>

                <div class="tab-content">
                    <!-- /.tab-pane -->
                    <div class="active tab-pane" id="settings">
                        <form action="@Url.Action("ProfileUser")" method="post" class="form-horizontal">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary("", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(m => m.FullName, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Address, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                                </div>
                            </div>
                            @if (User.Identity.Name == Model.UserName)
                            {
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-save"></i> Cập Nhật</button>
                                    </div>
                                </div>
                            }
                        </form>
                    </div>
                    <!-- /.tab-pane -->
                    <div id="changepassword" class="tab-pane">
                            @using (Ajax.BeginForm("ChangePassword", "AspNetUser",null, new AjaxOptions { OnSuccess = "ChangePasswordSuccess", OnFailure = "ShowPopUpError('Lỗi!')", HttpMethod = "Post", AllowCache = false }, new { @class = "form-horizontal", role = "form" }))
                            {

                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(m => changePasswordViewModel.OldPassword, new { @class = "col-md-3 control-label" })
                                    <div class="col-md-6">
                                        @Html.PasswordFor(m => changePasswordViewModel.OldPassword, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => changePasswordViewModel.NewPassword, new { @class = "col-md-3 control-label" })
                                    <div class="col-md-6">
                                        @Html.PasswordFor(m => changePasswordViewModel.NewPassword, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => changePasswordViewModel.ConfirmPassword, new { @class = "col-md-3 control-label" })
                                    <div class="col-md-6">
                                        @Html.PasswordFor(m => changePasswordViewModel.ConfirmPassword, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-6">
                                        <input type="submit" value="Đổi Mật Khẩu" class="btn btn-success" />
                                    </div>
                                </div>
                            }
                        </div>
                  
                </div>
                <!-- /.tab-content -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Source Code/Areas/Admin/Views/AspNetUser/_DeleteModal.cshtml
@model ApplicationUser

@{
    Layout = null;
}

@using (Html.BeginForm("Delete", "AspNetUser", new { Id = Model.Id }, FormMethod.Post, new { name = "frm" }))
{
    <div class="modal-header bg-red">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Xoá Nhân Viên</h4>
    </div>

    <div class="modal-body">
        <!-- form start -->
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <h5>Bạn có chắc muốn xoá nhân viên @Model.FullName ?</h5>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <button type="submit" class="btn btn-default bg-red"><i class="fa fa-save"></i> Xoá</button>
    </div>
}


@Scripts.Render("~/bundles/jqueryval")

Source Code/Areas/Admin/Views/AspNetUser/_UserLoggedPartial.cshtml
@model ApplicationUser
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="~/Photos/Users/@Model.Avatar" class="user-image" alt="User Image">
        <span class="hidden-xs">@Model.FullName</span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="~/Photos/Users/@Model.Avatar" class="img-circle" alt="User Image">
            <p>
                @Model.FullName - Nhân Viên
                <small>Gia nhập ngày @(Warehouse.Models.Format.FormatDateTime(Model.DateRegister))</small>
            </p>
        </li>
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="@Url.Action("ProfileUser","AspNetUser")" class="btn btn-default btn-flat">Hồ sơ cá nhân</a>
            </div>
            <div class="pull-right">
                @using (Html.BeginForm("LogOff", "Account",new {area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    <input type="hidden" name="fromAdminArea" value="1" />
                    @Html.AntiForgeryToken()
                }
                <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Đăng xuất</a>
            </div>
        </li>
    </ul>
</li>